### ISSUE TITLE
Connexion

### ISSUE THREAD

**Issue by alkaj** [IN-DEV/webgossip#3]
interface de connexion

**Comment by alkaj** [comment]
joli travail @dansalomon2015 mm comme ce n'etait pas ta tache! ...
![screen shot 2015-07-08 at 22 59 15](https://cloud.githubusercontent.com/assets/11011363/8583542/403ef234-25c6-11e5-870a-ca2c139c402e.png)
ca nous permet d'avancer!

**Comment by lepatlamass** [comment]
mdrr

**Comment by dansalomon2015** [comment]
si c'était la tache de pat j'annule mon git. je vois qu'il se marre bien.
lol

2015-07-09 9:29 GMT+01:00 lepatlamass notifications@github.com:
