### ISSUE TITLE
Boite de dialogue passe partout

### ISSUE THREAD

**Issue by alkaj** [IN-DEV/webgossip#8]
Le traitement de ce composant a ete ouvert 'par erreur' sur le projet andro ce qu'en voulant fermer qque je m'en suis rendu compte. 
j'ouvre ce traitement ici pour les amelioration du composant car il est deja(La base bien sure) termine.
sa notice sera mise a jour sous peu. en voici un apercu:
![Utilisation dans le role 'Continuer'](https://cloud.githubusercontent.com/assets/11011363/8510281/e0acd320-22d4-11e5-89d9-e1e76a267a92.png)

**Comment by alkaj** [comment]
Bon on passe a la phase d'ameliorations.

**Comment by alkaj** [comment]
Bien vouloir lire la notice avant de se lancer dans l'utilisation!  
Les fichiers `demo.*` montrent une integration du composant.  
Le developpeur est responsable de la faire apparaitre ou disparaitre a sa guise( c'est lui qui gere le ng-show sur le composant. )

**Comment by alkaj** [comment]
c'est bon pour ce composant!

**Comment by lepatlamass** [comment]
tu do que le web

**Comment by alkaj** [comment]
je do le monitoring!

2015-07-06 21:59 GMT+01:00 lepatlamass notifications@github.com:

**Comment by alkaj** [comment]
c'est un coup de pousse a la @teamweb!

2015-07-06 22:02 GMT+01:00 Junior al kaj alkaj09@gmail.com:

**Comment by alkaj** [comment]
Bonjour IN-DEV/webgossip,
Junior al kaj vous a laissé un message sur IQ Elite 
Cliquez ici https://a.iqelite.com/j/Xg52bu/bl7/ pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : https://a.iqelite.com/common/unsubscribe/?code=a12701cf&email=reply@reply.github.com.
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by alkaj** [comment]
Bonjour,

Vous avez passé le test de Personnalité et nous avons le plaisir de vous informer que vos résultats sont maintenant disponibles. 

Cliquez ici : https://a.iqelite.com/entry/redirect/personality/5ba995ca0f823d47a100000c/0/            

Cordialement, 
L'équipe IQ Elite 



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : https://a.iqelite.com/common/unsubscribe/?code=a12701cf&email=reply@reply.github.com.
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by alkaj** [comment]
Bonjour,

Vous avez récemment passé un test de Personnalité et avez obtenu de très bons résultats ! Voulez-vous connaître vos résultats ?

Dernière chance : vos résultats seront automatiquement supprimés demain. 

Pour voir vos résultats GRATUITEMENT, il suffit de cliquer sur le lien suivant : https://a.iqelite.com/entry/redirect/personality/5ba995ca0f823d47a100000c/0/            

Cordialement, 
L'équipe IQ Elite 



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : https://a.iqelite.com/common/unsubscribe/?code=a12701cf&email=reply@reply.github.com.
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------
